import { ArrowRight, Flag, Target } from "lucide-react";
import type { ProfileState } from "../../../shared/study";

type Props = { profile: ProfileState; onView: (view: "flashcards" | "quizzes") => void };
export default function ExamPrep({ profile, onView }: Props) {
  const recent = new Set(profile.studyActivity.slice(-10).map((item) => item.id));
  const weak = profile.flashcardSets.flatMap((set) => set.cards.filter((card) => card.status !== "known" || card.starred).map((card) => ({ ...card, set: set.title }))).slice(0, 27);
  const days = [1, 3, 7, 14];
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700 dark:text-amber-300">Kế hoạch ôn kiểm tra</p><h1 className="mt-2 font-display text-4xl font-bold">Tôi sắp kiểm tra</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Chọn thời gian còn lại. Study Historia sẽ ưu tiên nội dung yếu và thẻ chưa chắc thay vì bắt bạn học lại mọi thứ.</p></div><section className="grid gap-3 sm:grid-cols-4">{days.map((day) => <button key={day} className="panel p-4 text-left transition hover:-translate-y-0.5 hover:border-amber-400" onClick={() => onView("flashcards")}><b>{day} ngày nữa</b><span className="mt-1 block text-xs text-slate-500">Ưu tiên {Math.min(27, weak.length)} mục yếu</span></button>)}</section><section className="panel p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-700 dark:text-amber-300">Danh sách ưu tiên</p><h2 className="mt-2 font-display text-2xl font-bold">Ôn điều cần nhất trước</h2></div><button className="primary-button" onClick={() => onView("quizzes")}><Target className="h-4 w-4" />Làm đề ngay</button></div>{weak.length ? <div className="mt-5 space-y-2">{weak.slice(0, 10).map((card) => <div key={card.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 dark:border-white/10"><Flag className="h-4 w-4 text-amber-600" /><span className="min-w-0 flex-1"><b className="block truncate text-sm">{card.front}</b><small className="text-xs text-slate-500">{card.set} · {recent.has(card.id) ? "vừa ôn gần đây" : "chưa chắc"}</small></span><ArrowRight className="h-4 w-4 text-slate-400" /></div>)}</div> : <p className="mt-6 text-sm text-slate-500">Chưa có thẻ yếu. Hãy tạo Flashcard để lập kế hoạch.</p>}</section></div>;
}
