import { BookOpen, Check, Flame, Layers3, Play, RotateCcw, Sparkles } from "lucide-react";
import { useState } from "react";
import { levelForXp, updateStudyStreak, type AppConfig, type ProfileState } from "../../../shared/study";

type Props = { profile: ProfileState; config: AppConfig; onView: (view: "flashcards" | "quizzes" | "museum") => void; onProfile: (profile: ProfileState, message?: string) => void };

export default function FocusHub({ profile, config, onView, onProfile }: Props) {
  const [miniStarted, setMiniStarted] = useState(false);
  const [miniStep, setMiniStep] = useState(0);
  const miniSteps = [{ label: "5–10 Flashcard", view: "flashcards" as const }, { label: "1–3 câu trắc nghiệm", view: "quizzes" as const }, { label: "1 câu đúng/sai", view: "quizzes" as const }, { label: "1 câu trả lời ngắn", view: "quizzes" as const }];
  const weakSets = profile.flashcardSets.flatMap((set) => {
    const uncertain = set.cards.filter((card) => card.status !== "known");
    return uncertain.length ? [{ set, count: uncertain.length, certainty: Math.round((set.cards.length - uncertain.length) / Math.max(1, set.cards.length) * 100) }] : [];
  }).sort((a, b) => a.certainty - b.certainty).slice(0, 6);
  const totalHeld = Object.values(profile.fragments).reduce((sum, value) => sum + Math.max(0, value), 0);
  const fragmentRows = config.characters.map((character) => ({ character, held: Math.min(character.fragmentTotal, Math.max(0, profile.fragments[character.id] ?? 0)) })).sort((a, b) => (b.held / Math.max(1, b.character.fragmentTotal)) - (a.held / Math.max(1, a.character.fragmentTotal)));
  const activityDates = new Set(profile.studyActivity.map((entry) => new Date(entry.occurredAt).toLocaleDateString("vi-VN")));
  const streak = profile.currentStreak || (() => { let value = 0; for (let offset = 0; offset < 365; offset += 1) { const day = new Date(); day.setHours(0, 0, 0, 0); day.setDate(day.getDate() - offset); if (!activityDates.has(day.toLocaleDateString("vi-VN"))) break; value += 1; } return value; })();
  const encouragement = ["Hôm nay chỉ cần tiến thêm một chút thôi.", "Không cần hoàn hảo. Chỉ cần bắt đầu.", "Ong quay lại rồi, mình học một chút nhé."][new Date().getDate() % 3];
  return <div className="space-y-6">
    <section className="rounded-3xl bg-gradient-to-br from-[#8d5d15] via-amber-500 to-yellow-400 p-6 text-white shadow-xl shadow-amber-500/20"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-100">Ong hôm nay thế nào?</p><h1 className="mt-2 font-display text-3xl font-bold">{encouragement}</h1><div className="mt-5 flex flex-wrap items-center gap-3"><button className="rounded-xl bg-white px-4 py-3 text-sm font-bold text-amber-900" onClick={() => { setMiniStarted(true); setMiniStep(0); }}><Play className="mr-2 inline h-4 w-4" />Học 10 phút</button><span className="rounded-xl bg-white/15 px-4 py-3 text-sm font-bold"><Flame className="mr-2 inline h-4 w-4" />Chuỗi học: {streak} ngày · Kỷ lục {profile.bestStreak || streak}</span></div></section>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <section className="panel p-6" aria-labelledby="smart-review-title"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700 dark:text-amber-300">Ôn lại thông minh</p><h2 id="smart-review-title" className="mt-2 font-display text-2xl font-bold">Những phần Ong chưa chắc</h2><p className="mt-2 text-sm leading-6 text-slate-500">Ưu tiên thẻ mới và thẻ chưa nhớ thay vì học lại toàn bộ.</p></div><RotateCcw className="h-6 w-6 text-amber-600" /></div>{weakSets.length ? <div className="mt-5 space-y-3">{weakSets.map(({ set, count, certainty }) => <div key={set.id} className="flex items-center gap-3 rounded-2xl border border-amber-100 p-3 dark:border-amber-400/15"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-800 dark:bg-amber-500/15 dark:text-amber-200"><BookOpen className="h-4 w-4" /></div><div className="min-w-0 flex-1"><b className="block truncate text-sm">{set.subject} · {set.topic || set.title}</b><span className="text-xs text-slate-500">{count} thẻ cần ôn · Độ chắc chắn {certainty}%</span></div><button className="secondary-button px-3 py-2 text-xs" onClick={() => onView("flashcards")}>Ôn ngay</button></div>)}</div> : <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-500/10 dark:text-amber-100">Chưa có phần yếu rõ ràng. Hãy học một bộ mới để hệ thống bắt đầu theo dõi.</p>}</section>
      <section className="panel p-6" aria-labelledby="fragment-vault-title"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700 dark:text-amber-300">Kho mảnh ghép</p><h2 id="fragment-vault-title" className="mt-2 font-display text-2xl font-bold">Mảnh đang giữ</h2></div><Layers3 className="h-6 w-6 text-amber-600" /></div><p className="mt-2 text-sm text-slate-500">Tổng cộng {totalHeld} mảnh; nhân vật gần hoàn thành được ưu tiên hiển thị.</p>{fragmentRows.length ? <div className="mt-5 space-y-4">{fragmentRows.slice(0, 5).map(({ character, held }) => <button key={character.id} className="block w-full text-left" onClick={() => onView("museum")}><div className="flex justify-between gap-3 text-sm"><b>{character.name}</b><span className="text-slate-500">{held}/{character.fragmentTotal}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-amber-100 dark:bg-amber-500/10"><div className="h-full rounded-full bg-gradient-to-r from-amber-500 to-yellow-300" style={{ width: `${Math.min(100, held / Math.max(1, character.fragmentTotal) * 100)}%` }} /></div></button>)}</div> : <p className="mt-5 text-sm text-slate-500">Chưa có nhân vật hoặc mảnh ghép. Hãy mở Bảo tàng sau khi Admin thêm dữ liệu.</p>}</section>
    </div>
    <section className="panel p-6"><div className="flex items-start gap-3"><Sparkles className="mt-1 h-5 w-5 text-amber-600" /><div className="min-w-0 flex-1"><h2 className="font-display text-xl font-bold">Cấu trúc một phiên 10 phút</h2><p className="mt-2 text-sm leading-6 text-slate-500">Một mini-session có mục tiêu nhỏ, đủ để duy trì nhịp học mà không tạo áp lực.</p>{miniStarted && <div className="mt-5 space-y-2" role="list" aria-label="Các chặng trong phiên học 10 phút">{miniSteps.map((step, index) => <div key={step.label} className="flex items-center gap-3 rounded-xl border border-amber-100 p-3 dark:border-amber-400/15"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${index < miniStep ? "bg-amber-500 text-white" : "bg-amber-50 text-amber-800 dark:bg-amber-500/10 dark:text-amber-200"}`}>{index < miniStep ? <Check className="h-4 w-4" /> : index + 1}</span><span className="flex-1 text-sm font-bold">{step.label}</span>{index === miniStep && <button className="secondary-button px-3 py-2 text-xs" onClick={() => { onView(step.view); const nextStep = Math.min(miniSteps.length, miniStep + 1); setMiniStep(nextStep); if (nextStep === miniSteps.length) { const occurredAt = new Date().toISOString(); const xpEarned = 10; const streaked = updateStudyStreak(profile, occurredAt); onProfile({ ...streaked, xp: profile.xp + xpEarned, level: levelForXp(profile.xp + xpEarned), lastActivityAt: occurredAt, studyActivity: [{ id: `mini-${occurredAt}`, occurredAt, kind: "flashcard", quantity: 1, durationSeconds: 600, xpEarned }, ...profile.studyActivity] }, "Đã hoàn thành phiên Học 10 phút và nhận 10 XP."); } }}>{index === 0 ? "Bắt đầu" : "Mở"}</button>}</div>)}</div>}</div></div></section>
  </div>;
}
