import { BookOpen, CircleHelp, Map as MapIcon } from "lucide-react";
import type { ProfileState } from "../../../shared/study";

type Props = { profile: ProfileState; onView: (view: "flashcards" | "quizzes") => void };
export default function KnowledgeMap({ profile, onView }: Props) {
  const groups = new Map<string, { subject: string; topic: string; total: number; known: number; uncertain: number }>();
  profile.flashcardSets.forEach((set) => { const key = `${set.subject}::${set.topic || set.title}`; const current = groups.get(key) || { subject: set.subject, topic: set.topic || set.title, total: 0, known: 0, uncertain: 0 }; current.total += set.cards.length; current.known += set.cards.filter((card) => card.status === "known").length; current.uncertain += set.cards.filter((card) => card.status === "learning" || card.status === "new").length; groups.set(key, current); });
  const entries = Array.from(groups.values()).map((item) => ({ ...item, status: item.total === 0 ? "Chưa học" : item.known === item.total ? "Chắc" : item.known / item.total >= .5 ? "Cần ôn" : "Chưa chắc", progress: item.total ? Math.round(item.known / item.total * 100) : 0 }));
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700 dark:text-amber-300">Bản đồ kiến thức</p><h1 className="mt-2 font-display text-4xl font-bold">Nhìn thấy đường đi của mình</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Mỗi chủ đề được phân loại theo mức độ chắc chắn để Ong biết nên học mới hay quay lại ôn.</p></div><section className="grid gap-4 sm:grid-cols-4">{["Chắc", "Cần ôn", "Chưa chắc", "Chưa học"].map((status) => <div key={status} className="panel p-4"><b className="text-sm">{status}</b><span className="mt-2 block font-display text-3xl font-bold">{entries.filter((entry) => entry.status === status).length}</span></div>)}</section>{entries.length ? <section className="grid gap-4 md:grid-cols-2">{entries.map((entry) => <article key={`${entry.subject}-${entry.topic}`} className="panel p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-amber-700 dark:text-amber-300">{entry.subject}</p><h2 className="mt-1 font-display text-xl font-bold">{entry.topic}</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800 dark:bg-amber-500/10 dark:text-amber-200">{entry.status}</span></div><div className="mt-5 flex items-center gap-3"><div className="h-3 flex-1 overflow-hidden rounded-full bg-amber-100 dark:bg-amber-500/10"><div className="h-full rounded-full bg-amber-500" style={{ width: `${entry.progress}%` }} /></div><b className="text-sm">{entry.progress}%</b></div><p className="mt-2 text-xs text-slate-500">{entry.known}/{entry.total} thẻ chắc · {entry.uncertain} thẻ cần xem lại</p><div className="mt-4 flex gap-2"><button className="secondary-button px-3 py-2 text-xs" onClick={() => onView("flashcards")}><BookOpen className="mr-2 inline h-4 w-4" />Flashcard</button><button className="secondary-button px-3 py-2 text-xs" onClick={() => onView("quizzes")}><CircleHelp className="mr-2 inline h-4 w-4" />Quiz</button></div></article>)}</section> : <div className="panel grid min-h-56 place-items-center p-8 text-center"><MapIcon className="h-7 w-7 text-amber-600" /><p className="mt-3 text-sm text-slate-500">Tạo Flashcard trước, bản đồ sẽ tự hiện các chủ đề.</p></div>}</div>;
}
