import { BookOpen, CheckCircle2, Clock3, Dices, Flame, LockKeyhole, Puzzle, RotateCcw, Sparkles, Target, Trophy } from "lucide-react";
import { assembleCharacter, getCharacterProgress } from "../../../shared/fragmentSystem";
import type { AppConfig, ProfileState, StudyAccount } from "../../../shared/study";
import MuseumEnhanced from "./MuseumEnhanced";

type LearningView = "flashcards" | "quizzes" | "pomodoro" | "achievements" | "wheel" | "focus" | "history";

type FragmentWay = { icon: string; title: string; description: string; milestone: string; view?: LearningView; label: string; status: "active" | "configured" | "planned" };

const fragmentWays: FragmentWay[] = [
  { icon: "🃏", title: "Học Flashcard", description: "Học đủ thẻ, trả lời đúng liên tiếp, hoàn thành bộ hoặc quay lại ôn thẻ từng sai.", milestone: "Theo mốc bộ thẻ và độ chính xác; không nhận 1 mảnh cho mỗi thẻ.", view: "flashcards", label: "Mở Flashcard", status: "active" },
  { icon: "📝", title: "Hoàn thành Đề kiểm tra", description: "Kết quả trắc nghiệm, Đúng/Sai và trả lời ngắn có thể mở các mốc thưởng.", milestone: "Hoàn thành đề, đạt 70% / 80% / 90% / 100% hoặc cải thiện điểm.", view: "quizzes", label: "Mở Đề kiểm tra", status: "active" },
  { icon: "🍅", title: "Hoàn thành Pomodoro", description: "Mỗi phiên hoàn thành ưu tiên XP; mảnh ghép chỉ xuất hiện ở mốc xa.", milestone: "Ví dụ: phiên thứ 10 hoặc hoàn thành chuỗi phiên đã đặt.", view: "pomodoro", label: "Mở Pomodoro", status: "active" },
  { icon: "🏆", title: "Mở khóa Thành tích", description: "Một số thành tích mang XP, huy hiệu, danh hiệu và mảnh ghép.", milestone: "Thành tích cấp cao có thể trao mảnh hiếm.", view: "achievements", label: "Xem Thành tích", status: "active" },
  { icon: "🔥", title: "Duy trì chuỗi học tập", description: "Học liên tục qua nhiều ngày để tiến tới các mốc thưởng lớn hơn.", milestone: "Các mốc tham khảo: 3, 7, 14, 30 và 60 ngày.", view: "history", label: "Xem Lịch sử học", status: "configured" },
  { icon: "🎯", title: "Hoàn thành mục tiêu học tập", description: "Đủ giờ học, Flashcard, đề kiểm tra, chương hoặc mục tiêu điểm số.", milestone: "Phần thưởng chỉ trao khi đạt mục tiêu lớn đã được cấu hình.", view: "focus", label: "Mở Tiến trình", status: "configured" },
  { icon: "🔄", title: "Ôn lại kiến thức sai", description: "Quay lại câu đã sai, ôn lại và trả lời đúng để được tính vào tiến trình.", milestone: "Khuyến khích sửa lỗi, không thưởng tức thì cho một lần trả lời đơn lẻ.", view: "focus", label: "Mở Ôn tập", status: "configured" },
  { icon: "⚡", title: "Thử thách học tập đặc biệt", description: "Challenge ngày hoặc tuần kết hợp nhiều hoạt động học tập.", milestone: "Ví dụ: 30 Flashcard + 1 Pomodoro hoặc 5 đề kiểm tra.", status: "planned", label: "Theo cấu hình" },
  { icon: "🎡", title: "Vòng quay phần thưởng", description: "Vé quay có giới hạn, chỉ mở sau các điều kiện học tập nhất định.", milestone: "Có thể nhận mảnh thường, hiếm, đặc biệt hoặc XP.", view: "wheel", label: "Mở Vòng quay", status: "active" },
  { icon: "📚", title: "Hoàn thành chương học", description: "Hoàn tất nội dung, Flashcard và bài kiểm tra của một chương.", milestone: "Một mảnh hoặc phần thưởng đặc biệt theo cấu hình chương.", status: "planned", label: "Theo cấu hình" },
  { icon: "🌟", title: "Thành tích đặc biệt", description: "Các mảnh hiếm dành cho hành trình dài, nhiều chương, điểm cao liên tục hoặc nhiều Pomodoro.", milestone: "Không thể nhận bằng vài Flashcard đơn lẻ.", view: "achievements", label: "Xem Thành tích", status: "configured" },
  { icon: "🎁", title: "Phần thưởng sự kiện", description: "Sự kiện học tập theo chủ đề có thể trao mảnh nhân vật riêng.", milestone: "Chỉ xuất hiện trong thời gian và điều kiện sự kiện.", status: "planned", label: "Theo sự kiện" },
];

export default function MuseumJourney({ account, profile, config, onView, onProfile }: { account: StudyAccount; profile: ProfileState; config: AppConfig; onView: (view: LearningView) => void; onProfile: (profile: ProfileState, message?: string) => void }) {
  return <>
    <MuseumEnhanced account={account} profile={profile} config={config} />
    <section className="panel mt-7 p-6" aria-labelledby="fragment-ways-title"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700 dark:text-amber-300">Tiến trình phần thưởng</p><h2 id="fragment-ways-title" className="mt-2 font-display text-2xl font-bold">🧩 Cách nhận mảnh ghép</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Mảnh ghép là phần thưởng cho tiến trình học có ý nghĩa. Hệ thống dùng các mốc đủ xa để khuyến khích học sâu, không nhận 1 mảnh cho mỗi thẻ hoặc mỗi phiên.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-amber-100 px-3 py-2 text-sm font-bold text-amber-900 dark:bg-amber-500/15 dark:text-amber-100"><Puzzle className="h-4 w-4" />{Object.values(profile.fragments).reduce((sum, value) => sum + Math.max(0, value), 0)} mảnh đang giữ</span></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{fragmentWays.map((way) => <article key={way.title} className="rounded-2xl border border-amber-100 bg-white/70 p-4 dark:border-amber-400/15 dark:bg-white/[.035]"><div className="flex items-start gap-3"><span className="text-2xl" aria-hidden="true">{way.icon}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-base font-bold">{way.title}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${way.status === "active" ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-500/15 dark:text-emerald-200" : way.status === "configured" ? "bg-amber-100 text-amber-800 dark:bg-amber-500/15 dark:text-amber-200" : "bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-300"}`}>{way.status === "active" ? "Đang áp dụng" : way.status === "configured" ? "Theo tiến trình" : "Chờ cấu hình"}</span></div><p className="mt-2 text-sm leading-6 text-slate-500">{way.description}</p><p className="mt-2 text-xs font-bold leading-5 text-amber-800 dark:text-amber-200">Mốc: {way.milestone}</p>{way.view && <button className="secondary-button mt-3 px-3 py-2 text-xs" onClick={() => onView(way.view!)}><CheckCircle2 className="h-3.5 w-3.5" />{way.label}</button>}</div></div></article>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Mảnh ghép có thể thuộc nhóm thường, hiếm, đặc biệt hoặc sự kiện. Khi nhận được, mảnh sẽ đi vào Bộ sưu tập → Nhân vật → Tiến trình ghép hình.</p></section>
    {config.characters.length > 0 && <section className="panel mt-7 p-6" aria-labelledby="fragment-map-title" aria-describedby="fragment-map-status">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700 dark:text-amber-300">Bộ sưu tập mảnh ghép</p><h2 id="fragment-map-title" className="mt-2 font-display text-2xl font-bold">Ghép từng mảnh, mở từng câu chuyện</h2><p id="fragment-map-status" role="status" aria-live="polite" className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Mỗi ô đại diện cho mảnh ghép đã có hoặc còn thiếu của một nhân vật. Khi số mảnh đạt mốc do quản trị viên đặt, tiểu sử và timeline được mở trong Bảo tàng.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-amber-100 px-3 py-2 text-sm font-bold text-amber-900 dark:bg-amber-500/15 dark:text-amber-100"><Puzzle className="h-4 w-4" />{Object.values(profile.fragments).reduce((sum, value) => sum + Math.max(0, value), 0)} mảnh đang giữ</span></div>
      <div className="mt-6 grid gap-4 lg:grid-cols-2">{config.characters.map((character) => {
        const progress = getCharacterProgress(profile, character);
        const held = Math.min(character.fragmentTotal, progress.collectedPieceIds.length || Math.max(0, profile.fragments[character.id] ?? 0));
        const unlocked = progress.status === "unlocked";
        const ready = progress.status === "ready";
        const stage = unlocked ? "complete" : held > 0 ? "assembling" : "collecting";
        const stageLabel = unlocked ? "Giai đoạn 5 · Đọc lịch sử" : ready ? "Giai đoạn 4 · Sẵn sàng ghép" : held > 0 ? "Giai đoạn 2 · Đang ghép" : "Giai đoạn 1 · Thu thập";
        const tiles = Array.from({ length: character.fragmentTotal }, (_, index) => index);
        return <article className={`rounded-3xl border border-amber-100 bg-amber-50/50 p-4 dark:border-amber-400/15 dark:bg-amber-500/[.04] fragment-assembly fragment-assembly--${stage} ${unlocked ? "achievement-card--unlocked" : ""}`} key={character.id}><div className="flex items-start justify-between gap-4"><div><h3 className="font-display text-lg font-bold">{character.name}</h3><p className="mt-1 text-sm text-slate-500">{stageLabel} · {unlocked ? "Đã mở khóa — xem chi tiết trong Bảo tàng." : `Còn ${character.fragmentTotal - held} mảnh để mở khóa.`}</p>{character.sourceName && character.sourceUrl ? <a className="mt-2 inline-block text-xs font-bold text-amber-800 underline dark:text-amber-200" href={character.sourceUrl} target="_blank" rel="noreferrer">Nguồn: {character.sourceName}</a> : <p role="status" className="mt-2 text-xs font-bold text-orange-700 dark:text-orange-300">Cảnh báo: nội dung này chưa có nguồn xác minh.</p>}</div>{!unlocked && <LockKeyhole className="h-5 w-5 shrink-0 text-amber-700 dark:text-amber-300" aria-label="Nhân vật chưa mở khóa" />}</div><div className="mt-4 grid grid-cols-6 gap-1.5" role="img" aria-label={`${character.name}: ${held} trên ${character.fragmentTotal} mảnh ghép đã thu thập`}>{tiles.map((tile) => <span key={tile} className={`fragment-tile ${tile < held ? "fragment-tile--held" : "fragment-tile--missing"}`} aria-hidden="true" />)}</div><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-bold text-amber-800 dark:text-amber-200">{held}/{character.fragmentTotal} mảnh ghép · {progress.status === "unlocked" ? "Đã dùng để mở khóa" : "Đang sở hữu"}</p>{ready && <button className="primary-button px-3 py-2 text-xs" onClick={() => { const result = assembleCharacter(profile, character); if (result.assembled) onProfile(result.profile, `Đã hoàn thành hình và mở khóa ${character.name}.`); }}><Puzzle className="h-3.5 w-3.5" />Ghép hình hoàn chỉnh</button>}{unlocked && <button className="secondary-button px-3 py-2 text-xs" onClick={() => onView("history")}><BookOpen className="h-3.5 w-3.5" />Đọc lịch sử</button>}</div></article>;
      })}</div>
    </section>}
  </>;
}
