import { cn } from "@/lib/utils";
import { ChevronLeft, ExternalLink, History, LockKeyhole, MapPin, ScrollText } from "lucide-react";
import { useState } from "react";
import type { AppConfig, ProfileState, StudyAccount } from "../../../shared/study";

export default function MuseumEnhanced({ account, profile, config }: { account: StudyAccount; profile: ProfileState; config: AppConfig }) {
  const [selectedId, setSelectedId] = useState<string | null>(null); const [museumQuery, setMuseumQuery] = useState(""); const [museumStatus, setMuseumStatus] = useState("all"); const filteredCharacters = config.characters.filter((character) => { const fragments = profile.fragments[character.id] ?? 0; const unlocked = fragments >= character.fragmentTotal; return (!museumQuery || `${character.name} ${character.role} ${character.summary}`.toLowerCase().includes(museumQuery.toLowerCase())) && (museumStatus === "all" || (museumStatus === "unlocked" && unlocked) || (museumStatus === "locked" && !unlocked)); });
  const selected = config.characters.find((item) => item.id === selectedId);
  const isAdmin = account.role === "Admin" || account.role === "Founder";
  if (!config.characters.length) return <><Heading eyebrow="Bảo tàng hành trình" title="Học để mở khóa những câu chuyện" text="Bảo tàng không có dữ liệu mẫu. Mọi nhân vật, nguồn và ảnh đều do Admin/Founder biên tập." /><Empty title="Chưa có dữ liệu nhân vật" text={isAdmin ? "Mở Admin Panel để thêm nội dung lịch sử đã xác minh, nguồn trích dẫn và ảnh có ghi nhận nguồn." : "Admin/Founder sẽ công bố dữ liệu lịch sử đã được xác minh khi sẵn sàng."} /></>;
  if (selected) { const fragments = profile.fragments[selected.id] ?? 0; const unlocked = fragments >= selected.fragmentTotal; return <><button aria-label="Quay lại danh sách bảo tàng" onClick={() => setSelectedId(null)} className="secondary-button mb-6"><ChevronLeft className="h-4 w-4" />Quay lại bảo tàng</button><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900"><div className="grid min-h-64 place-items-center bg-gradient-to-br from-[#2d211a] via-[#5c4028] to-[#9a6a2f] md:min-h-80">{selected.imageUrl ? <img src={selected.imageUrl} alt={unlocked ? selected.name : "Nhân vật đang khóa"} className={cn("h-full w-full object-cover", !unlocked && "blur-md brightness-50")} /> : <History className="h-14 w-14 text-white/25" />}{!unlocked && <span className="absolute inline-flex items-center gap-2 rounded-full bg-slate-950/70 px-4 py-2 text-sm font-bold text-white"><LockKeyhole className="h-4 w-4" />Cần {selected.fragmentTotal - fragments} mảnh ghép nữa</span>}</div><article className="p-6 sm:p-9"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-700">{selected.role || "Nhân vật lịch sử"}</p><h1 className="mt-2 font-display text-4xl font-bold text-slate-950 dark:text-white">{unlocked ? selected.name : "Nhân vật chưa mở khóa"}</h1>{unlocked ? <><p className="mt-5 max-w-3xl text-sm leading-7 text-amber-700 dark:text-slate-300">{selected.biography || selected.summary || "Nội dung tiểu sử đang được Admin/Founder bổ sung."}</p><div className="mt-7 grid gap-4 md:grid-cols-2"><Info icon={MapPin} title="Thông tin" text={[selected.birthYear && `Sinh: ${selected.birthYear}`, selected.deathYear && `Mất: ${selected.deathYear}`, selected.hometown && `Quê quán: ${selected.hometown}`].filter(Boolean).join(" · ") || "Chưa có thông tin."} /><Info icon={ScrollText} title="Nguồn tham khảo" text={selected.sourceName || "Chưa có nguồn được nhập."} link={selected.sourceUrl} /></div><section className="mt-8"><h2 className="font-display text-2xl font-bold">Mốc lịch sử</h2>{selected.timeline.length ? <div className="mt-5 space-y-4 border-l-2 border-amber-200 pl-5 dark:border-amber-400/30">{selected.timeline.map((item) => <div key={item.id} className="relative"><span className="absolute -left-[31px] top-1.5 h-3 w-3 rounded-full bg-amber-500" /><b>{item.title}</b><p className="mt-1 text-sm leading-6 text-slate-500">{item.content}</p></div>)}</div> : <p className="mt-3 text-sm text-slate-500">Chưa có mốc lịch sử được nhập.</p>}</section></> : <p className="mt-5 text-sm leading-7 text-slate-500">Tiếp tục học tập để thu thập đủ mảnh ghép, sau đó mở khóa tiểu sử, mốc lịch sử và nguồn tham khảo.</p>}</article></div></>;
  }
  return <><Heading eyebrow="Bảo tàng hành trình" title="Học để mở khóa những câu chuyện" text="Thu thập mảnh ghép để khám phá các nhân vật lịch sử Việt Nam." /><div className="panel mb-5 grid gap-3 p-4 sm:grid-cols-[1fr_220px]"><input aria-label="Tìm nhân vật trong bảo tàng" value={museumQuery} onChange={(e) => setMuseumQuery(e.target.value)} placeholder="Tìm theo tên, vai trò, mô tả" className="input mt-0" /><select aria-label="Lọc trạng thái mảnh ghép" value={museumStatus} onChange={(e) => setMuseumStatus(e.target.value)} className="input mt-0"><option value="all">Tất cả nhân vật</option><option value="unlocked">Đã mở khóa</option><option value="locked">Còn khóa</option></select></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filteredCharacters.map((character) => { const fragments = profile.fragments[character.id] ?? 0; const unlocked = fragments >= character.fragmentTotal; return <button key={character.id} aria-label={`${unlocked ? "Xem nhân vật" : "Xem trạng thái khóa của nhân vật"}: ${unlocked ? character.name : "Nhân vật chưa mở khóa"}`} onClick={() => setSelectedId(character.id)} className="overflow-hidden rounded-3xl border border-slate-200 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:border-amber-300 dark:border-white/10 dark:bg-slate-900"><div className="relative grid h-48 place-items-center bg-gradient-to-br from-[#3a281e] to-[#805b32]">{character.imageUrl ? <img src={character.imageUrl} alt={unlocked ? character.name : "Nhân vật đang khóa"} className={cn("h-full w-full object-cover", !unlocked && "blur-md brightness-50")} /> : <History className="h-12 w-12 text-white/25" />}{!unlocked && <LockKeyhole className="absolute h-7 w-7 text-white" />}</div><div className="p-5"><p className="text-xs font-bold uppercase tracking-widest text-amber-700">{character.role || "Nhân vật lịch sử"}</p><h2 className="mt-1 font-display text-xl font-bold">{unlocked ? character.name : "Nhân vật chưa mở khóa"}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{unlocked ? character.summary || "Chưa có mô tả." : "Thu thập mảnh ghép để khám phá câu chuyện."}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-amber-300 to-amber-600" style={{ width: `${Math.min(100, fragments / character.fragmentTotal * 100)}%` }} /></div><p className="mt-2 text-xs font-bold text-slate-500">{fragments}/{character.fragmentTotal} mảnh ghép</p></div></button>; })}</div></>;
}
function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700 dark:text-amber-300">{eyebrow}</p><h1 className="mt-2 font-display text-3xl font-bold text-slate-950 dark:text-white sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{text}</p></div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="grid min-h-52 place-items-center rounded-3xl border border-dashed border-slate-300 bg-white/60 p-8 text-center dark:border-white/10 dark:bg-white/[.025]"><div><History className="mx-auto h-7 w-7 text-slate-400" /><b className="mt-3 block">{title}</b><p className="mt-1 max-w-md text-sm leading-6 text-slate-500">{text}</p></div></div>; }
function Info({ icon: Icon, title, text, link }: { icon: typeof History; title: string; text: string; link?: string }) { return <div className="rounded-2xl bg-slate-50 p-4 dark:bg-white/5"><Icon className="h-5 w-5 text-amber-700" /><b className="mt-3 block text-sm">{title}</b><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p>{link && <a aria-label={`Mở nguồn tham khảo ${title}`} target="_blank" rel="noreferrer" href={link} className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-amber-700">Mở nguồn <ExternalLink className="h-3 w-3" /></a>}</div>; }
