import fs from 'node:fs';
const cssPath = '/home/ubuntu/study-historia/client/src/index.css';
let css = fs.readFileSync(cssPath, 'utf8');
css += '\n.achievement-card--unlocked, .session-complete { transition: transform var(--motion-standard) var(--ease-out), box-shadow var(--motion-standard) var(--ease-out); }\n@media (prefers-reduced-motion: no-preference) {\n  .achievement-card--unlocked { animation: achievement-unlock 520ms var(--ease-out) both; }\n  .session-complete { animation: session-complete 360ms var(--ease-out) both; }\n}\n@keyframes achievement-unlock { from { opacity: .72; transform: translateY(4px) scale(.98); } to { opacity: 1; transform: translateY(0) scale(1); } }\n@keyframes session-complete { from { opacity: .82; transform: translateY(3px); } to { opacity: 1; transform: translateY(0); } }\n';
fs.writeFileSync(cssPath, css);
const museumPath = '/home/ubuntu/study-historia/client/src/pages/MuseumJourney.tsx';
let museum = fs.readFileSync(museumPath, 'utf8');
museum = museum.replace('<section className="panel mt-7 p-6" aria-labelledby="fragment-map-title">', '<section className="panel mt-7 p-6" aria-labelledby="fragment-map-title" aria-describedby="fragment-map-status">');
museum = museum.replace('<p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Mỗi ô đại diện', '<p id="fragment-map-status" role="status" aria-live="polite" className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Mỗi ô đại diện');
museum = museum.replace('<article className="rounded-3xl border', '<article className={`rounded-3xl border ${unlocked ? "achievement-card--unlocked" : ""}`');
fs.writeFileSync(museumPath, museum);
const homePath = '/home/ubuntu/study-historia/client/src/pages/Home.tsx';
let home = fs.readFileSync(homePath, 'utf8');
home = home.replace('<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950', '<div role="status" aria-live="polite" className="session-complete mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950');
home = home.replace('className={cn("rounded-2xl border p-4", isOpen ?', 'className={cn("achievement-card--unlocked rounded-2xl border p-4", isOpen ?');
fs.writeFileSync(homePath, home);
const testPath = '/home/ubuntu/study-historia/client/src/pages/Home.cards.test.ts';
let test = fs.readFileSync(testPath, 'utf8');
test = test.replace('    expect(source).toContain("applyStudyActivityRewards");', '    expect(source).toContain("applyStudyActivityRewards");\n    expect(source).toContain("session-complete");\n    expect(source).toContain("aria-live=\\"polite\\"");');
fs.writeFileSync(testPath, test);
