import fs from 'node:fs';
const homePath = '/home/ubuntu/study-historia/client/src/pages/Home.tsx';
let home = fs.readFileSync(homePath, 'utf8');
home = home.replace('const [rapidSeconds, setRapidSeconds] = useState(0); useEffect(() => { if (studyMode !== "rapid") { setRapidSeconds(0); return; } const started = Date.now(); const timer = window.setInterval(() => setRapidSeconds(Math.floor((Date.now() - started) / 1000)), 1000); return () => window.clearInterval(timer); }, [studyMode]);', 'const [rapidSeconds, setRapidSeconds] = useState(0); const [rapidExpired, setRapidExpired] = useState(false); const rapidLimitSeconds = 60; useEffect(() => { if (studyMode !== "rapid") { setRapidSeconds(0); setRapidExpired(false); return; } const started = Date.now(); const timer = window.setInterval(() => { const elapsed = Math.floor((Date.now() - started) / 1000); setRapidSeconds(elapsed); if (elapsed >= rapidLimitSeconds) { setRapidExpired(true); window.clearInterval(timer); } }, 1000); return () => window.clearInterval(timer); }, [studyMode]);');
home = home.replace('const answerChoice = (choice: string) => { setFlipped(true); mark(choice.trim().toLowerCase() === card.back.trim().toLowerCase() ? "known" : "learning"); };', 'const normalizeAnswer = (value: string) => value.trim().replace(/\\s+/g, " ").toLocaleLowerCase("vi"); const answerChoice = (choice: string) => { setFlipped(true); mark(normalizeAnswer(choice) === normalizeAnswer(card.back) ? "known" : "learning"); }; const answerWrite = () => { if (!writeAnswer.trim()) return; setFlipped(true); mark(normalizeAnswer(writeAnswer) === normalizeAnswer(card.back) ? "known" : "learning"); setWriteAnswer(""); };');
home = home.replace('const restartSession = () => { setSessionStats({ total: 0, known: 0, learning: 0, xp: 0 }); setShowReport(false); setIndex(0); setFlipped(false); setWriteAnswer(""); };', 'const restartSession = () => { setSessionStats({ total: 0, known: 0, learning: 0, xp: 0 }); setShowReport(false); setIndex(0); setFlipped(false); setWriteAnswer(""); setRapidSeconds(0); setRapidExpired(false); };');
home = home.replace('{studyMode === "rapid" && <div className="mt-4 flex items-center justify-between rounded-xl bg-amber-50 px-4 py-3 text-sm font-bold text-amber-900 dark:bg-amber-400/10 dark:text-amber-100"><span>Phiên tốc độ · {rapidSeconds}s</span><span>Đã chấm {sessionStats.total} thẻ</span></div>}', '{studyMode === "rapid" && <div className="mt-4 flex items-center justify-between rounded-xl bg-amber-50 px-4 py-3 text-sm font-bold text-amber-900 dark:bg-amber-400/10 dark:text-amber-100"><span>Phiên tốc độ · {rapidSeconds}/{rapidLimitSeconds}s</span><span>{rapidExpired ? "Đã hết giờ" : `Đã chấm ${sessionStats.total} thẻ`}</span></div>}');
home = home.replace('onClick={() => { setFlipped(true); setWriteAnswer(""); }} className="secondary-button">Kiểm tra', 'onClick={answerWrite} className="secondary-button">Kiểm tra');
home = home.replace('<button onClick={() => mark("learning")} className="secondary-button text-rose-600">Cần ôn lại</button>', '<button disabled={rapidExpired} onClick={() => mark("learning")} className="secondary-button text-rose-600 disabled:opacity-50">Cần ôn lại</button>');
home = home.replace('<button onClick={() => mark("known")} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-bold text-white">Đã nhớ</button>', '<button disabled={rapidExpired} onClick={() => mark("known")} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Đã nhớ</button>');
home = home.replace('<button onClick={() => setShowReport(true)} className="secondary-button">Báo cáo phiên</button>', '<button onClick={() => setShowReport(true)} className="secondary-button">{rapidExpired ? "Xem kết quả tốc độ" : "Báo cáo phiên"}</button>');
fs.writeFileSync(homePath, home);

const studyPath = '/home/ubuntu/study-historia/shared/study.ts';
let study = fs.readFileSync(studyPath, 'utf8');
study = study.replace('kind: "flashcard" | "quiz";', 'kind: "flashcard" | "quiz" | "wheel";');
study = study.replace('item.kind !== "flashcard" && item.kind !== "quiz"', 'item.kind !== "flashcard" && item.kind !== "quiz" && item.kind !== "wheel"');
fs.writeFileSync(studyPath, study);

const wheelPath = '/home/ubuntu/study-historia/client/src/pages/WheelEnhanced.tsx';
let wheel = fs.readFileSync(wheelPath, 'utf8');
wheel = wheel.replace('import { levelForXp, type AppConfig, type ProfileState, type WheelReward } from "../../../shared/study";', 'import { applyStudyActivityRewards, levelForXp, type AppConfig, type ProfileState, type WheelReward } from "../../../shared/study";');
const old = 'const next = { ...profile, wheelTickets: profile.wheelTickets - 1, xp: profile.xp + (reward.kind === "xp" ? reward.value : 0), fragments: reward.kind === "fragment" ? { ...profile.fragments, general: (profile.fragments.general ?? 0) + reward.value } : profile.fragments }; next.level = levelForXp(next.xp); setResult(reward); setSpinning(false); onProfile(next, `Nhận được ${reward.label}.`);';
const replacement = 'const base = { ...profile, wheelTickets: Math.max(0, profile.wheelTickets - 1), inventory: reward.kind === "item" ? [...profile.inventory, reward.label] : profile.inventory, ownedBadges: reward.kind === "badge" ? Array.from(new Set([...profile.ownedBadges, reward.label])) : profile.ownedBadges }; const activity = applyStudyActivityRewards(base, { id: `wheel-${Date.now()}-${reward.id}`, occurredAt: new Date().toISOString(), kind: "wheel", quantity: reward.kind === "fragment" ? Math.max(10, reward.value * 10) : 0, durationSeconds: 0, xpEarned: reward.kind === "xp" ? reward.value : 0 }, config); const next = { ...activity.profile, wheelTickets: activity.profile.wheelTickets + (reward.kind === "ticket" ? reward.value : 0) }; next.level = levelForXp(next.xp); setResult(reward); setSpinning(false); onProfile(next, `Nhận được ${reward.label}.`);';
if (!wheel.includes(old)) throw new Error('Wheel reward block not found');
wheel = wheel.replace(old, replacement);
fs.writeFileSync(wheelPath, wheel);
